### ISSUE TITLE
Reconstructing HDR image in VDS dataset

### ISSUE THREAD

**Issue by skchen1993** [Siyeong-Lee/hdr_vds_dataset#1]
Hello, this series of research (Deep chain HDRI, Deep Recursive HDRI, Deep arbitrary HDRI) really inspire me a lot. I really admire your ideas!

We are trying to reproduce your experiment, but we have encountered some issues about generating the HDR file from the LDR stack provided in the VDS dataset.

As far as I know, the algorithm proposed by Devebec require the exposure time of each LDR image to reconstruct the corresponding HDR image. But the VDS dataset used in the research does not provide such information.

Is it possible to generate an HDR file from the LDR stack without the exposure time for each LDR image? or approximate the HDR file result from the LDR stack without exposure time?

Thank you very much, looking forward to your reply!

**Comment by Siyeong-Lee** [comment]
Sorry for the late reply.  First, thank you for your interest in our work.

As mentioned in the paper, we assumed that the image with the appropriate exposure has EV 0 from the observation that the appropriate exposure level for each scene is different. 

Through Equation 1 of the paper, the relative exposure time between the reference image, the EV0 image, and other images can be calculated.

In addition, assuming ISO-100 and f/1 in the EV-0 situation, the exposure time is 1 second, so the exposure time of each image can be estimated.

**Comment by skchen1993** [comment]
Thank you so much!!
I would give a try!
